name: Format Code

on:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format Python Code
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Format with Black
        run: black custom_components/

      - name: Sort imports with isort
        run: isort custom_components/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-format Python code"
          file_pattern: "custom_components/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
