name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}  # Remove 'v' prefix if present
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update manifest version
        run: |
          sed -i 's/"version": ".*"/"version": "${{ steps.version.outputs.version }}"/' custom_components/solarmax/manifest.json

      - name: Create ZIP file
        run: |
          cd custom_components
          zip -r ../solarmax-${{ steps.version.outputs.version }}.zip solarmax/

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: solarmax-${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
