name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: HACS Validation
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: brands

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest Validation
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
        with:
          path: "./custom_components/solarmax"

  lint:
    runs-on: "ubuntu-latest"
    name: Code Quality
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      
      - name: Check formatting with Black
        run: black --check --diff custom_components/
      
      - name: Check import sorting with isort
        run: isort --check-only --diff custom_components/
